name: CI/CD for AVA Website

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t ava-dog-site .

      # Optional: Push to DockerHub or GHCR
      # - name: Log in to DockerHub
      #   run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      # - name: Push Docker image
      #   run: docker push ava-dog-site
